#Spring
spring:
  datasource:
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gakken9-3839?useUnicode=true&characterEncoding=UTF-8
server:
  servlet:
    context-path: /
ans-url:
  NOTICE_REMOTE_URL_appLoginCheck: http://59.110.141.18:8090/ans/v1/3/device
  NOTICE_REMOTE_URL_unReadGet: http://59.110.141.18:8090/ans/v1/3/message/unread
  NOTICE_REMOTE_URL_sendMessage: http://59.110.141.18:8090/ans/v1/3/message
  NOTICE_REMOTE_URL_errorData: http://59.110.141.18:8090/ans/v1/3/message/errorData
  token: U2FsdGVkX1/fVLL43pIy0qGxgAdRS2lP81dbP/rVqS0tRArTBAN0Hd5NOhoa6Je1
mail:
  host: smtp.sinways.com.cn
  username: gakken@sinways.com.cn
  password: gakken@123
  protocol: smtp
  port: 465
  smtp-port: 465
  smtp-auth: true
  ssl-enable: true
  starttls-enable: true
  starttls-required: true
# 检证API
# 学研API
gakken-api:
  #本仮APIフラグ（是否正式调用api）
  realApi: false
  #REQUEST_URL
  requestUrl: https://idgear-qas.x.itecgw.jp/gid/services/
  #SOAP認証用UsernameToken
  user: GEDWESUNTQ
  #SOAP認証用Password
  password: c56de89c45dcf40d0d76418abdf7ad2a
  #特権アクセストークン
  priToken: 5fb8cf8936b8v62f802fc6b8a0cd3b28
  #サービスサイトコード
  serviceCd: GEDWESSSIQ
  #サービスショップコード
  shopCd: GEDWESSSHQ
  #GakkenTID履歴キー
  gakkenTidHistKey: get_info_hist
  #メールアドレスキー
  gakkenMailKey: get_mail_address
  #指導者コードキー
  teacherCodeKey: get_teacher_code_01
  #サービスサイトコード2
  serviceCd2: GEDWESSSIP

#domain
learningpark-domain:
  #  LE-AWS検証環境
  domain: http://localhost:8080/
#mail:
#  host: smtp.sinways.com.cn
#  username: gakken@sinways.com.cn
#  password: gakken@123
#  protocol: smtp
#  port: 465
#  properties.mail.smtp.port: 465
#  properties.mail.smtp.auth: true
#  properties.mail.smtp.ssl.enable: true
#  properties.mail.smtp.starttls.enable: true
#  properties.mail.smtp.starttls.required: true

ueditor:
  urlPrefix: http://localhost:8080
localFlag: true

#saml2の設定
saml2:
  regId: http://localhost:8090/v9.1/saml2/service-provider-metadata/manamirusp
  #IdP エンティティID
  idpEntityId: https://localhost/ssoIdp/saml2/idp/metadata.php
  #IdP SSOエンドポイント
  idpSSOLocation: https://localhost/ssoIdp/saml2/idp/SSOService.php
  #SPの秘密鍵
  spPrivateKey: /cert/sp.pem
  #SPの共通鍵
  spCertificate: /cert/sp.crt
  #IDPの共通鍵
  idpCertificate: /cert/idp.crt
  # 認証失敗
  failureUrl: /login/onair